- name: Remove build dependencies
  apt:
    pkg:
      - bison
      - build-essential
      - clang-11
      - cmake
      - cpp
      - flex
      - g++
      - g++-10
      - g++-9
      - gcc-10
      - ninja-build
      - python2
      - zlib1g-dev
    state: absent
    autoremove: yes
