- name: Install postgis
  import_tasks: tasks/postgres-extensions/01-postgis.yml

- name: Install pgrouting
  import_tasks: tasks/postgres-extensions/02-pgrouting.yml

- name: Install pgtap
  import_tasks: tasks/postgres-extensions/03-pgtap.yml

- name: Install pg_cron
  import_tasks: tasks/postgres-extensions/04-pg_cron.yml

- name: Install pgaudit
  import_tasks: tasks/postgres-extensions/05-pgaudit.yml

- name: Install pgjwt
  import_tasks: tasks/postgres-extensions/06-pgjwt.yml

- name: Install pgsql-http
  import_tasks: tasks/postgres-extensions/07-pgsql-http.yml

- name: Install plpgsql_check
  import_tasks: tasks/postgres-extensions/08-plpgsql_check.yml

- name: Install pg-safeupdate
  import_tasks: tasks/postgres-extensions/09-pg-safeupdate.yml

# - name: Install timescaledb
#   import_tasks: tasks/postgres-extensions/10-timescaledb.yml

- name: Install pljava
  import_tasks: tasks/postgres-extensions/11-pljava.yml

- name: Install plv8
  import_tasks: tasks/postgres-extensions/12-plv8.yml