- name: Run migrate.sh script
  shell: ./migrate.sh
  register: retval
  when: ebssurrogate_mode
  args:
    chdir: /opt/migrations/db
  failed_when: retval.rc != 0

- name: Create /root/MIGRATION-AMI file
  file:
    path: "/root/MIGRATION-AMI"
    state: touch
  when: ebssurrogate_mode
