- name: Install postgis
  import_tasks: tasks/postgres-extensions/01-postgis.yml

- name: Install pgrouting
  import_tasks: tasks/postgres-extensions/02-pgrouting.yml

- name: Install pgtap
  import_tasks: tasks/postgres-extensions/03-pgtap.yml

- name: Install pg_cron
  import_tasks: tasks/postgres-extensions/04-pg_cron.yml

- name: Install pgaudit
  import_tasks: tasks/postgres-extensions/05-pgaudit.yml

- name: Install pgjwt
  import_tasks: tasks/postgres-extensions/06-pgjwt.yml

- name: Install pgsql-http
  import_tasks: tasks/postgres-extensions/07-pgsql-http.yml

- name: Install plpgsql_check
  import_tasks: tasks/postgres-extensions/08-plpgsql_check.yml

- name: Install pg-safeupdate
  import_tasks: tasks/postgres-extensions/09-pg-safeupdate.yml

- name: Install timescaledb
  import_tasks: tasks/postgres-extensions/10-timescaledb.yml

- name: Install wal2json
  import_tasks: tasks/postgres-extensions/11-wal2json.yml

- name: Install pljava
  import_tasks: tasks/postgres-extensions/12-pljava.yml

- name: Install plv8
  import_tasks: tasks/postgres-extensions/13-plv8.yml

- name: Install pg_plan_filter
  import_tasks: tasks/postgres-extensions/14-pg_plan_filter.yml

- name: Install pg_net
  import_tasks: tasks/postgres-extensions/15-pg_net.yml

- name: Install rum
  import_tasks: tasks/postgres-extensions/16-rum.yml

- name: Install pg_hashids
  import_tasks: tasks/postgres-extensions/17-pg_hashids.yml

- name: Install pgsodium
  import_tasks: tasks/postgres-extensions/18-pgsodium.yml

- name: Install pg_graphql
  import_tasks: tasks/postgres-extensions/19-pg_graphql.yml

- name: Install pg_stat_monitor
  import_tasks: tasks/postgres-extensions/20-pg_stat_monitor.yml

- name: Install auto_explain
  import_tasks: tasks/postgres-extensions/21-auto_explain.yml
