# pgTAP
- name: pgTAP - download latest release
  get_url:
    url: "https://github.com/theory/pgtap/archive/v{{ pgtap_release }}.tar.gz"
    dest: /tmp/pgtap-{{ pgtap_release }}.tar.gz
    checksum: "{{ pgtap_release_checksum }}"
    timeout: 60

- name: pgTAP - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/pgtap-{{ pgtap_release }}.tar.gz
    dest: /tmp
  become: yes

- name: pgTAP - install
  make:
    chdir: /tmp/pgtap-{{ pgtap_release }}
    target: install
  become: yes
  
- name: pgTAP - cleanup
  file:
    state: absent
    path: /tmp/pgtap-{{ pgtap_release }}