# plpgsql_check
- name: plpgsql_check - download & install dependencies
  apt:
    pkg:
      - libicu-dev
    update_cache: yes
    install_recommends: no

- name: plpgsql_check - download latest release
  get_url:
    url: "https://github.com/okbob/plpgsql_check/archive/refs/tags/v{{ plpgsql_check_release }}.tar.gz"
    dest: /tmp/plpgsql_check-{{ plpgsql_check_release }}.tar.gz
    checksum: "{{ plpgsql_check_release_checksum }}"

- name: plpgsql_check - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/plpgsql_check-{{ plpgsql_check_release }}.tar.gz
    dest: /tmp
  become: yes

- name: plpgsql_check - clean
  make:
    chdir: /tmp/plpgsql_check-{{ plpgsql_check_release }}
    target: clean
  become: yes

- name: plpgsql_check - install
  make:
    chdir: /tmp/plpgsql_check-{{ plpgsql_check_release }}
    target: install
  become: yes

- name: plpgsql_check - remove build dependencies
  apt:
    pkg:
      - libicu-dev
    state: absent