# pg-safeupdate
- name: pg-safeupdate - download latest release
  get_url:
    url: "https://github.com/eradman/pg-safeupdate/archive/refs/tags/{{ pg_safeupdate_release }}.tar.gz"
    dest: /tmp/pg_safeupdate-{{ pg_safeupdate_release }}.tar.gz
    checksum: "{{ pg_safeupdate_release_checksum }}"

- name: pg-safeupdate - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/pg_safeupdate-{{ pg_safeupdate_release }}.tar.gz
    dest: /tmp
  become: yes

- name: pg-safeupdate - build
  make:
    chdir: /tmp/pg-safeupdate-{{ pg_safeupdate_release }}
  become: yes

- name: pg-safeupdate - install
  make:
    chdir: /tmp/pg-safeupdate-{{ pg_safeupdate_release }}
    target: install
  become: yes