# plv8
- name: plv8 - download & install dependencies
  apt:
    pkg:
      - build-essential
      - ca-certificates
      - curl
      - git-core
      - gpp
      - cpp
      - pkg-config
      - apt-transport-https
      - cmake
      - libc++-dev
      - libc++abi-dev
      - libc++1
      - libglib2.0-dev
      - libtinfo5
      - libc++abi1
      - ninja-build
      - python
    update_cache: yes
    install_recommends: no

- name: plv8 - download latest release
  git:
    repo: https://github.com/plv8/plv8.git
    dest: /tmp/plv8
    version: 3656177d384e3e02b74faa8e2931600f3690ab59
  become: yes

- name: Create a symbolic link
  file:
    src: /lib/aarch64-linux-gnu/libc++.so.1
    dest: /lib/aarch64-linux-gnu/libc++.so
    state: link
  when: platform == "arm64"

- name: plv8 - build
  make:
    chdir: /tmp/plv8
  become: yes

- name: plv8 - install
  make:
    chdir: /tmp/plv8
    target: install
  become: yes