# pg_net
- name: pg_net - download & install dependencies
  apt:
    pkg:
      - libcurl4-gnutls-dev
    update_cache: yes
    install_recommends: no

- name: pg_net - download latest release
  get_url:
    url: "https://github.com/supabase/pg_net/archive/refs/tags/v{{pg_net_release}}.tar.gz"
    dest: /tmp/pg_net-{{ pg_net_release }}.tar.gz
    checksum: "{{ pg_net_release_checksum }}"
    timeout: 60

- name: pg_net - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/pg_net-{{ pg_net_release }}.tar.gz
    dest: /tmp
  become: yes

- name: pg_net - build
  make:
    chdir: /tmp/pg_net-{{ pg_net_release }}
  become: yes

- name: pg_net - install
  make:
    chdir: /tmp/pg_net-{{ pg_net_release }}
    target: install
  become: yes