# pg_stat_monitor
- name: pg_stat_monitor - download and install dependencies
  git:
    repo: https://github.com/percona/pg_stat_monitor.git
    dest: /tmp/pg_stat_monitor
    version: "{{ pg_stat_monitor_release }}"
  become: yes

- name: pg_stat_monitor build 
  make:
    chdir: /tmp/pg_stat_monitor
    params: USE_PGXS=1

- name: pg_stat_monitor install
  make:
    chdir: /tmp/pg_stat_monitor
    target: install
    params: USE_PGXS=1

- name: pg_stat_monitor cleanup
  file:
    state: absent
    path: /tmp/pg_stat_monitor