# vault

- name: vault - download vault
  get_url:
    url: "https://github.com/supabase/vault/archive/refs/tags/v{{ vault_release }}.tar.gz"
    dest: /tmp/vault-{{ vault_release }}.tar.gz
    checksum: "{{ vault_release_checksum }}"
    timeout: 60

- name: vault - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/vault-{{ vault_release }}.tar.gz
    dest: /tmp
  become: yes

- name: vault - build
  make:
    chdir: /tmp/vault-{{ vault_release }}
  become: yes

- name: vault - install
  make:
    chdir: /tmp/vault-{{ vault_release }}
    target: install
  become: yes
