# pgvector
- name: pgvector - download latest release
  git:
    repo: https://github.com/pgvector/pgvector.git
    dest: /tmp/pgvector
    version: '{{ pgvector_release }}'
  become: yes

- name: pgvector - build
  make:
    chdir: /tmp/pgvector
  become: yes

- name: pgvector - install
  make:
    chdir: /tmp/pgvector
    target: install
  become: yes
