port: 8085
host: 0.0.0.0
ref: {{ .ProjectRef }}
jwt_secret: {{ .JwtSecret }}
metric_collectors:
  - filesystem
  - meminfo
  - netdev
  - loadavg
  - cpu
  - diskstats
  - vmstat
node_exporter_additional_args:
  - "--collector.filesystem.ignored-mount-points=^/(boot|sys|dev|run).*"
  - "--collector.netdev.device-exclude=lo"
# cert_path: /etc/ssl/adminapi/server.crt
# key_path: /etc/ssl/adminapi/server.key
upstream_metrics_refresh_duration: 60s
pgbouncer_endpoints:
  - "postgres://pgbouncer:{{ .PgbouncerPassword }}@localhost:6543/pgbouncer"
fail2ban_socket: /var/run/fail2ban/fail2ban.sock
upstream_metrics_sources:
  - name: system
    url: "https://localhost:8085/metrics"
    labels_to_attach:
      - name: supabase_project_ref
        value: {{ .ProjectRef }}
      - name: service_type
        value: db
    skip_tls_verify: true
  - name: postgresql
    url: "http://localhost:9187/metrics"
    labels_to_attach:
      - name: supabase_project_ref
        value: {{ .ProjectRef }}
      - name: service_type
        value: postgresql
  - name: gotrue
    url: "http://localhost:9122/metrics"
    labels_to_attach:
      - name: supabase_project_ref
        value: {{ .ProjectRef }}
      - name: service_type
        value: gotrue
  - name: postgrest
    url: "http://localhost:3001/metrics"
    labels_to_attach:
      - name: supabase_project_ref
        value: {{ .ProjectRef }}
      - name: service_type
        value: postgrest
monitoring:
  disk_usage:
    enabled: true
upgrades_config:
  region: us-east-1
  s3_bucket_name: supabase-internal-artifacts-prod-bucket
  common_prefix: upgrades
  destination_dir: /tmp
firewall:
  enabled: true
  internal_ports:
    - 9187
    - 8085
    - 9122
  privileged_ports:
    - 22
  privileged_ports_allowlist:
    - 0.0.0.0/0
  filtered_ports:
    - 5432
    - 6543
  unfiltered_ports:
    - 80
    - 443
  managed_rules_file: /etc/nftables/supabase_managed.conf
pg_egress_collect_path: /tmp/pg_egress_collect.txt
health_reporting:
  api_url: {{ .SupabaseUrl }}
  project_token: {{ .ReportingToken }}
  check_services:
  #   - postgres
  #   - postgrest
