name: Release Migrations

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: [self-hosted, linux]
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Merging migration files
        run: cat $(ls -1) > ../migration-output.sql
        working-directory: ${{ github.workspace }}/migrations/db/migrations

      - name: configure aws credentials - staging
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}
          aws-region: "ap-southeast-1"

      - name: Deploy to S3 staging
        shell: bash
        run: aws s3 sync migrations/db s3://$AWS_S3_BUCKET/migrations/db --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PG_INIT_SCRIPT_S3_BUCKET_STAGING }}

      - name: configure aws credentials - prod
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.PROD_AWS_ROLE }}
          aws-region: "ap-southeast-1"

      - name: Deploy to S3 prod
        shell: bash
        run: aws s3 sync migrations/db s3://$AWS_S3_BUCKET/migrations/db --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PG_INIT_SCRIPT_S3_BUCKET_PROD }}
